language: python
python:
  - "3.8"
install:
  - pip install pipenv
  - pipenv install --system --dev --deploy

script:
  - python -m flake8
  - python -m mypy .
  - coverage run -m unittest discover src

after_success:
  - coverage report -m
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
  - bash <(curl -s https://codecov.io/bash)